/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TemaTest;


public class App {
    /**
     * Doar aici am variabile cu acces public, doar in APP.
     *Publice ca sa fie accesibile de InputHandler fara getter si setters
     * facand programul mai eficient, in plus, daca lucram direct in main,
     * era aceasi vizibilitate , fiind vizibile privatele in clasa curenta
     */

    public AllUsers users;
    private static InputHandler input;

    public App() {
        users = new AllUsers();
        Postare.reset();
        Comentariu.resetComments();
    }

    public static void main(java.lang.String[] strings) {
        if (strings == null || input == null) {
            App myApp = new App();
            input = new InputHandler(myApp);
            if (strings == null) {
                System.out.println("Hello world!");
                return;
            }
        }
            input.scanInput(strings);

    }


}

